using Unity.AI.Navigation;
using UnityEngine;

namespace HoldMyBeer.Gameplay.Adults
{
    /// <summary>
    /// Builds the school's NavMesh when the scene opens instead of shipping a baked
    /// asset: the level is generated by code, and navigation data produced by the same
    /// generator would be one more asset that can silently fail to serialise.
    ///
    /// Runs in Awake so the mesh exists before <c>NetworkPropSpawner.Start</c> places
    /// the supervisors — an agent enabled off-mesh logs an error and never moves.
    /// </summary>
    [RequireComponent(typeof(NavMeshSurface))]
    public sealed class RuntimeNavMeshBuilder : MonoBehaviour
    {
        private void Awake()
        {
            GetComponent<NavMeshSurface>().BuildNavMesh();
        }
    }
}
